# Generated by Django 4.1.2 on 2022-10-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(-1, 'Default'), (0, 'Running'), (1, 'Completed'), (2, 'Error')], default=-1, null=True)),
                ('swagger_file', models.FileField(max_length=1024, upload_to='media', verbose_name='')),
                ('result_dir', models.FilePathField(blank=True, max_length=1024, null=True, path='media', verbose_name='')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
