# generated by fastapi-codegen:
#   filename:  app_7.yaml
#   timestamp: 2022-10-11T21:09:45+00:00

from __future__ import annotations

from fastapi import FastAPI

from common.factories import create_factory_class

from .models import Marketplace

app = FastAPI(
    title="Автомобильный маркетплейс (Хакатон)",
    description="Справочный сервис, который содержит опубликованный на автовитрине официального сайта ВТБ [https://www.vtb.ru/personal/avtokredity/avtovitrina/]() каталог автомобилей с их характеристиками, фотографиями, стоимостью и ориентировочным ежемесячным платежом при оформлении в кредит.",
    version="0.4.4",
    # servers=[{"url": "https://epa.api.vtb.ru/openapi"}],
)


@app.get("/marketplace", response_model=Marketplace)
def marketplace_marketplace_get() -> Marketplace:
    """
    Marketplace
    """
    return create_factory_class(Marketplace).build()
